// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDequn4sEcIGahFkJYB_4LgEQ6JeFBxis',
    appId: '1:429626530882:web:2c7fe9bb5ce1aab7aee1db',
    messagingSenderId: '429626530882',
    projectId: 'pokemon-app-5234f',
    authDomain: 'pokemon-app-5234f.firebaseapp.com',
    storageBucket: 'pokemon-app-5234f.appspot.com',
    measurementId: 'G-SF2Q8X3FV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzHwj8ggB7wvHHMay8lkHGWAmnFNd2AGk',
    appId: '1:429626530882:android:b3f5635c57484632aee1db',
    messagingSenderId: '429626530882',
    projectId: 'pokemon-app-5234f',
    storageBucket: 'pokemon-app-5234f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPA9-PBqzeL_i7kchBAuMtW5iHqH2hR9A',
    appId: '1:429626530882:ios:44c4c5ceda4e9eb5aee1db',
    messagingSenderId: '429626530882',
    projectId: 'pokemon-app-5234f',
    storageBucket: 'pokemon-app-5234f.appspot.com',
    iosBundleId: 'com.example.pokemon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPA9-PBqzeL_i7kchBAuMtW5iHqH2hR9A',
    appId: '1:429626530882:ios:44c4c5ceda4e9eb5aee1db',
    messagingSenderId: '429626530882',
    projectId: 'pokemon-app-5234f',
    storageBucket: 'pokemon-app-5234f.appspot.com',
    iosBundleId: 'com.example.pokemon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDequn4sEcIGahFkJYB_4LgEQ6JeFBxis',
    appId: '1:429626530882:web:df2189ab197d0c01aee1db',
    messagingSenderId: '429626530882',
    projectId: 'pokemon-app-5234f',
    authDomain: 'pokemon-app-5234f.firebaseapp.com',
    storageBucket: 'pokemon-app-5234f.appspot.com',
    measurementId: 'G-46T8RJ73GN',
  );
}
